name: CI

on:
  push:
  pull_request:

concurrency:
  # Cancel older runs on the same branch when you push new commits
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10          # avoid hung jobs

    strategy:
      matrix:
        python-version: ['3.10', '3.11']  # nice signal: supports multiple versions
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip                  # speeds up installs on repeat runs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (core only; perf excluded to avoid flakiness)
        run: |
          mkdir -p reports
          pytest -m "not performance" \
            --junitxml=reports/junit.xml \
            --html=reports/report.html --self-contained-html

      - name: Upload reports (always)
        if: always()                 # still get the HTML report even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-py${{ matrix.python-version }}
          path: reports
          retention-days: 7